site_name: The Land - Minecraft Server Documentation
site_url: https://squaremanran.github.io/TheLandMC/
repo_name: squaremanran/thelandmc
repo_url: https://github.com/squaremanran/thelandmc

nav:
  - index.md
  - Bedrock:
    - bedrock/windows10-mobile.md
    - bedrock/xbox.md
    - bedrock/switch.md
  - Features:
    - features/spawn.md
    - features/armorstandeditor.md
    - features/autocrafting.md
    - features/deepslate-instamine.md

theme:
  name: material
  logo:
  favicon: assets/troll.png
  features:
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      accent: grey
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      accent: grey
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  
edit_uri: edit/main/docs/
